server:
 port: 8081
spring:
 application:
  name: wagu-post
 cloud:
  config:
   discovery:
    enable: true
    service-id: wagu-config

zookeeper:
 host: localhost:2181
 groupId: wagu

kafka:
 topic:
  post: post
 bootstrap:
  servers: localhost:9092
 consumer:
  group-id: post-group
